# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Package Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]

jobs:
  Run-Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set Process Environment
      run: |
         touch .dev
         echo CHANNELACCESSTOKEN =${{ secrets.TESTCHANNELACCESSTOKEN }} >> .env
         echo CHANNELSECRET =${{ secrets.TESTCHANNELSECRET }} >> .env
         echo USERID =${{ secrets.TESTUSERID }} >> .env
         echo LAHRUNTESTFROM =$(echo git rev-parse --short "$GITHUB_SHA") >> .env
    - run: npm ci
    - run: npm test
